/** 記事 slug 変更時の旧 URL → 新 URL リダイレクト（末尾スラッシュ付き） */
export const ARTICLE_REDIRECTS: Record<string, string> = {
  '/articles/aburakoji-takemaru-recommended-books/':
    '/articles/abiko-takemaru-recommended-books/',
  '/articles/dogo-shusuke-recommended-books/':
    '/articles/michio-shusuke-recommended-books/',
  '/articles/miyashita-nato-recommended-books/':
    '/articles/miyashita-natsu-recommended-books/',
  '/articles/saika-tahi-recommended-books/':
    '/articles/saihate-tahi-recommended-books/',
  '/articles/takashi-yusuke-recommended-books/':
    '/articles/kishi-yusuke-recommended-books/',
  '/articles/shimmoto-riko-recommended-books/':
    '/articles/shimamoto-rio-recommended-books/',
  '/articles/awatake-tsutomu-recommended-books/':
    '/articles/awasaka-tsumao-recommended-books/',
  '/articles/hironobu-nozawa-recommended-books/':
    '/articles/ouchi-yoko-recommended-books/',
  '/articles/yoshihara-tadao-recommended-books/':
    '/articles/kaiba-yoshikazu-recommended-books/',
  '/articles/sakurai-atsuko-recommended-books/':
    '/articles/endo-junko-recommended-books/',
  '/articles/life-theater-of-recommended-books/':
    '/articles/kanno-teruyo-recommended-books/',
  '/articles/485-japan-national-route-recommended-books/':
    '/articles/harada-yasutaba-recommended-books/',
  '/articles/ikeoka-ryosuke-recommended-books/':
    '/articles/nakabayashi-ryosuke-recommended-books/',
  '/articles/line-ryomo-recommended-books/':
    '/articles/kiryu-yuzo-recommended-books/',
  '/articles/tadatsugu-sakai-recommended-books/':
    '/articles/sakai-kenkame-recommended-books/',
  '/articles/jojima-akihiko-recommended-books/':
    '/articles/joshima-akihiko-recommended-books/',
  '/articles/kambayashi-akatsuki-recommended-books/':
    '/articles/kanbayashi-satoru-recommended-books/',
  '/articles/fc-vancouver-whitecaps-recommended-books/':
    '/articles/hirano-jun-recommended-books/',
  '/articles/carp-hiroshima-toyo-recommended-books/':
    '/articles/go-seong-ho-recommended-books/',
  '/articles/egami-kaoru-recommended-books/':
    '/articles/ekuni-kaori-recommended-books/',
  '/articles/imamura-ry-suke-recommended-books/':
    '/articles/imamura-ryosuke-recommended-books/',
  '/articles/toyoda-k-ji-recommended-books/':
    '/articles/toyoda-koji-recommended-books/',
  '/articles/fukunaga-reiz--recommended-books/':
    '/articles/fukunaga-reizo-recommended-books/',
  '/articles/kanahara-hitomi-recommended-books/':
    '/articles/kanehara-hitomi-recommended-books/',
  '/articles/kenj--haku-recommended-books/':
    '/articles/kenjo-haku-recommended-books/',
};
